# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ufo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WoffMetadataCopyright(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WoffMetadataCopyright()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWoffMetadataCopyright(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WoffMetadataCopyright
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WoffMetadataCopyright
    def Text(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatFont.Ufo.WoffMetadataText import WoffMetadataText
            obj = WoffMetadataText()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WoffMetadataCopyright
    def TextLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WoffMetadataCopyright
    def TextIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def WoffMetadataCopyrightStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddText(builder, text): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def WoffMetadataCopyrightAddText(builder, text):
    """This method is deprecated. Please switch to AddText."""
    return AddText(builder, text)
def StartTextVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def WoffMetadataCopyrightStartTextVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartTextVector(builder, numElems)
def End(builder): return builder.EndObject()
def WoffMetadataCopyrightEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)