# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ufo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WoffMetadataCredit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WoffMetadataCredit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWoffMetadataCredit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WoffMetadataCredit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WoffMetadataCredit
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataCredit
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataCredit
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataCredit
    def Dir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataCredit
    def Class_(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(5)
def WoffMetadataCreditStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def WoffMetadataCreditAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddUrl(builder, url): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)
def WoffMetadataCreditAddUrl(builder, url):
    """This method is deprecated. Please switch to AddUrl."""
    return AddUrl(builder, url)
def AddRole(builder, role): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(role), 0)
def WoffMetadataCreditAddRole(builder, role):
    """This method is deprecated. Please switch to AddRole."""
    return AddRole(builder, role)
def AddDir(builder, dir): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(dir), 0)
def WoffMetadataCreditAddDir(builder, dir):
    """This method is deprecated. Please switch to AddDir."""
    return AddDir(builder, dir)
def AddClass_(builder, class_): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(class_), 0)
def WoffMetadataCreditAddClass_(builder, class_):
    """This method is deprecated. Please switch to AddClass_."""
    return AddClass_(builder, class_)
def End(builder): return builder.EndObject()
def WoffMetadataCreditEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)