# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ufo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WoffMetadataExtensionItem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WoffMetadataExtensionItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWoffMetadataExtensionItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WoffMetadataExtensionItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WoffMetadataExtensionItem
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataExtensionItem
    def Names(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatFont.Ufo.WoffMetadataExtensionName import WoffMetadataExtensionName
            obj = WoffMetadataExtensionName()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WoffMetadataExtensionItem
    def NamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WoffMetadataExtensionItem
    def NamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # WoffMetadataExtensionItem
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatFont.Ufo.WoffMetadataExtensionValue import WoffMetadataExtensionValue
            obj = WoffMetadataExtensionValue()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WoffMetadataExtensionItem
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WoffMetadataExtensionItem
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def Start(builder): builder.StartObject(3)
def WoffMetadataExtensionItemStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def WoffMetadataExtensionItemAddId(builder, id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, id)
def AddNames(builder, names): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(names), 0)
def WoffMetadataExtensionItemAddNames(builder, names):
    """This method is deprecated. Please switch to AddNames."""
    return AddNames(builder, names)
def StartNamesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def WoffMetadataExtensionItemStartNamesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartNamesVector(builder, numElems)
def AddValues(builder, values): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)
def WoffMetadataExtensionItemAddValues(builder, values):
    """This method is deprecated. Please switch to AddValues."""
    return AddValues(builder, values)
def StartValuesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def WoffMetadataExtensionItemStartValuesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartValuesVector(builder, numElems)
def End(builder): return builder.EndObject()
def WoffMetadataExtensionItemEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)