# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ufo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WoffMetadataCredits(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WoffMetadataCredits()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWoffMetadataCredits(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WoffMetadataCredits
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WoffMetadataCredits
    def Credits(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatFont.Ufo.WoffMetadataCredit import WoffMetadataCredit
            obj = WoffMetadataCredit()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WoffMetadataCredits
    def CreditsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WoffMetadataCredits
    def CreditsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def WoffMetadataCreditsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCredits(builder, credits): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(credits), 0)
def WoffMetadataCreditsAddCredits(builder, credits):
    """This method is deprecated. Please switch to AddCredits."""
    return AddCredits(builder, credits)
def StartCreditsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def WoffMetadataCreditsStartCreditsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartCreditsVector(builder, numElems)
def End(builder): return builder.EndObject()
def WoffMetadataCreditsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)