# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Ufo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WoffMetadataLicense(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WoffMetadataLicense()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWoffMetadataLicense(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WoffMetadataLicense
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WoffMetadataLicense
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataLicense
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WoffMetadataLicense
    def Text(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatFont.Ufo.WoffMetadataText import WoffMetadataText
            obj = WoffMetadataText()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WoffMetadataLicense
    def TextLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WoffMetadataLicense
    def TextIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def Start(builder): builder.StartObject(3)
def WoffMetadataLicenseStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddUrl(builder, url): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)
def WoffMetadataLicenseAddUrl(builder, url):
    """This method is deprecated. Please switch to AddUrl."""
    return AddUrl(builder, url)
def AddId(builder, id): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def WoffMetadataLicenseAddId(builder, id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, id)
def AddText(builder, text): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)
def WoffMetadataLicenseAddText(builder, text):
    """This method is deprecated. Please switch to AddText."""
    return AddText(builder, text)
def StartTextVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def WoffMetadataLicenseStartTextVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartTextVector(builder, numElems)
def End(builder): return builder.EndObject()
def WoffMetadataLicenseEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)